### ISSUE TITLE
Block explorer list

### ISSUE THREAD

**Issue by iamsmooth** [aeonix/aeonix.github.io#130]
I just merged some PRs to update the block explorer list, but I think the rest of the list is also stale.

Can anyone account for the other explorers in terms of who runs them and if they will be repaired, and if not, we should remove them.

**Comment by BigslimVdub** [comment]
(https://aeonblockexplorer.com/) - working on it
(https://aeonstats.com/) - still up
(https://aeonstats.info/) - working now

Both two others are working ok

**Comment by aeon1234** [comment]
FYI some time ago I made notes behind the entries in the reddit sidebar to know who owns which explorer:

[aeonblockexplorer.com](https://aeonblockexplorer.com) - [u/camothegeek](https://old.reddit.com/u/camothegeek)
[aeonstats.com](https://www.aeonstats.com) - [u/420coupe](https://old.reddit.com/u/420coupe)
[aeonstats.info](https://www.aeonstats.info) - *unknown*
[209.126.84.37:8081](http://209.126.84.37:8081) - [u/bigslimvdub](https://old.reddit.com/u/bigslimvdub)
[104.168.163.221](http://104.168.163.221) - [u/stoffu](https://old.reddit.com/u/stoffu)

sadly [aeonblockexplorer.com](https://aeonblockexplorer.com) is (still?) not working

**Comment by iamsmooth** [comment]
To remove the non-working explorer please submit PR
