### ISSUE TITLE
Layout gets broken on OSX/Chrome

### ISSUE THREAD

**Issue by stoffu** [aeonix/aeonix.github.io#24]
![screen shot 2018-01-16 at 8 31 21](https://user-images.githubusercontent.com/26077532/34965633-ed0bc4ca-fa98-11e7-8b58-f8e3663e7306.jpg)

- Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- macOS Sierra 10.12.6 (16G1114)

It used to be fine before. Not sure since when this issue existed.

**Comment by mattcode55** [comment]
Are there any errors in the JavaScript console? (Ctrl+Shift+J)

**Comment by stoffu** [comment]
Good question. And strange, the layout got back to normal...

If I don't see the same issue happen again for a while, I'll close this issue.
