### ISSUE TITLE
difference XMR<>AEON on fast syncing

### ISSUE THREAD

**Issue by aeon1234** [aeonix/aeonix.github.io#32]
website says:

>###  How is AEON different from Monero?

> Compared to Bitcoin variants, CryptoNote coins typically have higher verification, leading to more orphaned blocks. AEON helps this issue by using a 4-minute blocktime, reducing sync by **a factor of four**.

I think this changed to **a factor of 2** since monero forked to 2min block interval.

> Coupled with our lighter PoW, sync times on lower end devices can be improved by **10x or more**.

I'm not sure how this number will change then, so I started this issue instead of a PR.

can someone help me get this fixed? thank you.

**Comment by iamsmooth** [comment]
Just remove the phrase "reducing sync by a factor of four" from the first sentence. It doesn't really belong there. The second one is correct.
